import type { Metadata } from "next";
import "./globals.css";
import { RoleProvider } from "./context/RoleContext";
import { AuthProvider } from './context/authContext'
export const metadata: Metadata = {
  title: "MediApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <AuthProvider>
          <RoleProvider>
            {children}
          </RoleProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
