import type { Metadata } from "next";
import "./globals.css";
import { RoleProvider } from "./context/RoleContext";
import { AuthProvider } from './context/authContext'
import { DoctorProvider } from './context/doctorContext'

export const metadata: Metadata = {
  title: "MediApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <RoleProvider>
          <AuthProvider>
            <DoctorProvider>
              {children}
            </DoctorProvider>
          </AuthProvider>
        </RoleProvider>
      </body>
    </html>
  );
}
