import jsPDF from "jspdf";
import "jspdf-autotable";

export const generateReport = (symptomsData, diagnoses) => {
  const doc = new jsPDF();

  const logoUrl = "/images/logo.png";
  doc.addImage(logoUrl, "PNG", 10, 10, 30, 10);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("AI DIAGNOSIS REPORT", 80, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`All diagnoses generated by the model`, 80, 27);

  doc.text(
    "Generated on: " +
      new Intl.DateTimeFormat("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      }).format(new Date()),
    85,
    34
  );

  const tableColumn = ["Symptoms", "Predicted Diagnosis", "Final Diagnosis"];
  const tableRows = [];

  diagnoses.forEach((diagnosis) => {
    const patientSymptoms =
      symptomsData.find((s) => s.appointmentId === diagnosis.appointmentId)
        ?.symptoms || "N/A";

    const rowData = [
      Array.isArray(patientSymptoms)
        ? patientSymptoms.join(", ")
        : patientSymptoms,
      diagnosis.predictedDiagnosis,
      diagnosis.finalDiagnosis || "Pending",
    ];

    tableRows.push(rowData);
  });

  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 50,
    styles: { fontSize: 7 },
    headStyles: { fillColor: [0, 51, 153], textColor: 255 },
    alternateRowStyles: { fillColor: [240, 240, 240] },
    margin: { top: 10 },
  });

  // Footer
  doc.setFontSize(10);
  doc.text(
    "This report is system-generated.",
    14,
    doc.internal.pageSize.height - 30
  );
  doc.text(
    "For inquiries:nyagakristine@gmail.com",
    14,
    doc.internal.pageSize.height - 20
  );
  doc.text(
    "Page " + doc.internal.getNumberOfPages(),
    doc.internal.pageSize.width - 30,
    doc.internal.pageSize.height - 10
  );

  doc.save("Diagnosis_Report.pdf");
};
